name: piwork-quickstart
services:
  core:
    image: docker.io/pphboy/piwork-core:0.0.2-fb4f577da3b4-512ec778b267
    init: true
    user: "0:0"
    network_mode: host
    environment:
      PIWORK_ADMIN_ACCOUNT:
      PIWORK_ADMIN_PASSWORD:
      PIWORK_MODEL_PROVIDER:
      PIWORK_MODEL:
      PIWORK_API_KEY:
      PIWORK_MODEL_BASE_URL:
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: /var/lib/piwork/quickstart/core
        target: /var/lib/piwork/quickstart/core
        bind:
          create_host_path: true
    stop_grace_period: 60s
    restart: unless-stopped
