name: piwork-single-host
services:
  core:
    image: docker.io/pphboy/piwork-core:0.0.1-03395d0810f7-c70a7cb33564-dirty
    init: true
    user: "0:0"
    network_mode: host
    environment:
      PIWORK_ADMIN_ACCOUNT:
      PIWORK_ADMIN_PASSWORD:
      PIWORK_MODEL_PROVIDER:
      PIWORK_MODEL:
      PIWORK_API_KEY:
      PIWORK_MODEL_BASE_URL:
      PIWORK_DATA_DIR: /var/lib/piwork/examples/single-host/core
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: /var/lib/piwork/examples/single-host/core
        target: /var/lib/piwork/examples/single-host/core
        bind:
          create_host_path: true
    stop_grace_period: 60s
    restart: unless-stopped
  cli:
    image: docker.io/pphboy/piwork-cli:0.0.1-03395d0810f7-c70a7cb33564-dirty
    profiles: [cli]
    init: true
    user: "0:0"
    stdin_open: true
    tty: true
    environment:
      PIWORK_CORE_URL: http://host.docker.internal:7171
    extra_hosts: ["host.docker.internal:host-gateway"]
    volumes:
      - client-state:/var/lib/piwork/client
volumes:
  client-state:
    name: piwork-single-host-client-state
